- name: assign tags
  shell: ID=`maas {{maas_user}}  machines read hostname={{item.hostname}} | jq '.[] | .system_id' | tr -d '\"'`; 
            maas {{maas_user}} tag update-nodes {{item.tag}} add=$ID
  loop:
     - "{{ VM1 }}"
     - "{{ VM2 }}"
     - "{{ VM3 }}"
     - "{{ VM4 }}"
     - "{{ VM5 }}"
     - "{{ VM6 }}"
     - "{{ VM7 }}"
     - "{{ VM8 }}"
     - "{{ VM9 }}"
     